"""
Hardcoded demo corpus for MVP.

Contains ~20 verses from Matthew 3-4 and Mark 1 with token-level data.
All morphology codes follow Robinson-Pierpont format.
Senses are simplified from BDAG/Louw-Nida with explicit sourcing.
"""

# Demo tokens: (book, chapter, verse, position, surface, lemma, morph, is_red_letter)
DEMO_TOKENS = [
    # Matthew 3:2 - "Repent, for the kingdom of heaven has drawn near"
    ("Matthew", 3, 2, 1, "μετανοεῖτε", "μετανοέω", "V-PAM-2P", True),
    ("Matthew", 3, 2, 2, "ἤγγικεν", "ἐγγίζω", "V-RAI-3S", True),
    ("Matthew", 3, 2, 3, "γὰρ", "γάρ", "CONJ", True),
    ("Matthew", 3, 2, 4, "ἡ", "ὁ", "T-NSF", True),
    ("Matthew", 3, 2, 5, "βασιλεία", "βασιλεία", "N-NSF", True),
    ("Matthew", 3, 2, 6, "τῶν", "ὁ", "T-GPM", True),
    ("Matthew", 3, 2, 7, "οὐρανῶν", "οὐρανός", "N-GPM", True),
    # Matthew 4:17 - Same saying in different context
    ("Matthew", 4, 17, 1, "μετανοεῖτε", "μετανοέω", "V-PAM-2P", True),
    ("Matthew", 4, 17, 2, "ἤγγικεν", "ἐγγίζω", "V-RAI-3S", True),
    ("Matthew", 4, 17, 3, "γὰρ", "γάρ", "CONJ", True),
    ("Matthew", 4, 17, 4, "ἡ", "ὁ", "T-NSF", True),
    ("Matthew", 4, 17, 5, "βασιλεία", "βασιλεία", "N-NSF", True),
    ("Matthew", 4, 17, 6, "τῶν", "ὁ", "T-GPM", True),
    ("Matthew", 4, 17, 7, "οὐρανῶν", "οὐρανός", "N-GPM", True),
    # Mark 1:15 - "The time is fulfilled and the kingdom of God has drawn near; repent and believe in the gospel"
    ("Mark", 1, 15, 1, "πεπλήρωται", "πληρόω", "V-RPI-3S", True),
    ("Mark", 1, 15, 2, "ὁ", "ὁ", "T-NSM", True),
    ("Mark", 1, 15, 3, "καιρὸς", "καιρός", "N-NSM", True),
    ("Mark", 1, 15, 4, "καὶ", "καί", "CONJ", True),
    ("Mark", 1, 15, 5, "ἤγγικεν", "ἐγγίζω", "V-RAI-3S", True),
    ("Mark", 1, 15, 6, "ἡ", "ὁ", "T-NSF", True),
    ("Mark", 1, 15, 7, "βασιλεία", "βασιλεία", "N-NSF", True),
    ("Mark", 1, 15, 8, "τοῦ", "ὁ", "T-GSM", True),
    ("Mark", 1, 15, 9, "θεοῦ", "θεός", "N-GSM", True),
    ("Mark", 1, 15, 10, "μετανοεῖτε", "μετανοέω", "V-PAM-2P", True),
    ("Mark", 1, 15, 11, "καὶ", "καί", "CONJ", True),
    ("Mark", 1, 15, 12, "πιστεύετε", "πιστεύω", "V-PAM-2P", True),
    ("Mark", 1, 15, 13, "ἐν", "ἐν", "PREP", True),
    ("Mark", 1, 15, 14, "τῷ", "ὁ", "T-DSN", True),
    ("Mark", 1, 15, 15, "εὐαγγελίῳ", "εὐαγγέλιον", "N-DSN", True),
    # Matthew 5:3 - Beatitude: "Blessed are the poor in spirit"
    ("Matthew", 5, 3, 1, "μακάριοι", "μακάριος", "A-NPM", True),
    ("Matthew", 5, 3, 2, "οἱ", "ὁ", "T-NPM", True),
    ("Matthew", 5, 3, 3, "πτωχοὶ", "πτωχός", "A-NPM", True),
    ("Matthew", 5, 3, 4, "τῷ", "ὁ", "T-DSN", True),
    ("Matthew", 5, 3, 5, "πνεύματι", "πνεῦμα", "N-DSN", True),
    ("Matthew", 5, 3, 6, "ὅτι", "ὅτι", "CONJ", True),
    ("Matthew", 5, 3, 7, "αὐτῶν", "αὐτός", "P-GPM", True),
    ("Matthew", 5, 3, 8, "ἐστιν", "εἰμί", "V-PAI-3S", True),
    ("Matthew", 5, 3, 9, "ἡ", "ὁ", "T-NSF", True),
    ("Matthew", 5, 3, 10, "βασιλεία", "βασιλεία", "N-NSF", True),
    ("Matthew", 5, 3, 11, "τῶν", "ὁ", "T-GPM", True),
    ("Matthew", 5, 3, 12, "οὐρανῶν", "οὐρανός", "N-GPM", True),
    # Matthew 6:9-10 - Lord's Prayer opening
    ("Matthew", 6, 9, 1, "Πάτερ", "πατήρ", "N-VSM", True),
    ("Matthew", 6, 9, 2, "ἡμῶν", "ἐγώ", "P-1GP", True),
    ("Matthew", 6, 9, 3, "ὁ", "ὁ", "T-VSM", True),
    ("Matthew", 6, 9, 4, "ἐν", "ἐν", "PREP", True),
    ("Matthew", 6, 9, 5, "τοῖς", "ὁ", "T-DPM", True),
    ("Matthew", 6, 9, 6, "οὐρανοῖς", "οὐρανός", "N-DPM", True),
    ("Matthew", 6, 9, 7, "ἁγιασθήτω", "ἁγιάζω", "V-APM-3S", True),
    ("Matthew", 6, 9, 8, "τὸ", "ὁ", "T-NSN", True),
    ("Matthew", 6, 9, 9, "ὄνομά", "ὄνομα", "N-NSN", True),
    ("Matthew", 6, 9, 10, "σου", "σύ", "P-2GS", True),
    ("Matthew", 6, 10, 1, "ἐλθέτω", "ἔρχομαι", "V-AAM-3S", True),
    ("Matthew", 6, 10, 2, "ἡ", "ὁ", "T-NSF", True),
    ("Matthew", 6, 10, 3, "βασιλεία", "βασιλεία", "N-NSF", True),
    ("Matthew", 6, 10, 4, "σου", "σύ", "P-2GS", True),
]

# Demo senses: (lemma, sense_id, gloss, definition, source, weight, domain)
DEMO_SENSES = [
    # μετανοέω - key theological term with ambiguity
    (
        "μετανοέω",
        "metanoeo.1",
        "change one's mind",
        "to change one's way of thinking, with focus on cognitive reorientation",
        "BDAG",
        0.8,
        "cognitive",
    ),
    (
        "μετανοέω",
        "metanoeo.2",
        "repent",
        "to turn from sin with religious/moral implications",
        "BDAG",
        0.7,
        "religious",
    ),
    (
        "μετανοέω",
        "metanoeo.3",
        "turn around",
        "to fundamentally reorient one's life direction (Heb. שׁוּב concept)",
        "Louw-Nida",
        0.6,
        "behavioral",
    ),
    (
        "μετανοέω",
        "metanoeo.4",
        "think differently afterward",
        "post-cognitive shift, from μετά (after) + νοέω (think) - etymological",
        "LSJ",
        0.4,
        "etymological",
    ),
    # ἐγγίζω - spatial/temporal ambiguity
    (
        "ἐγγίζω",
        "eggizo.1",
        "draw near (spatially)",
        "to come near in physical space",
        "BDAG",
        0.9,
        "spatial",
    ),
    (
        "ἐγγίζω",
        "eggizo.2",
        "draw near (temporally)",
        "to approach in time, be imminent",
        "BDAG",
        0.85,
        "temporal",
    ),
    (
        "ἐγγίζω",
        "eggizo.3",
        "arrive",
        "to have reached, be present (perfective aspect)",
        "Louw-Nida",
        0.5,
        "arrival",
    ),
    # βασιλεία - kingdom/reign ambiguity
    (
        "βασιλεία",
        "basileia.1",
        "kingdom",
        "territory ruled by a king",
        "BDAG",
        0.7,
        "spatial",
    ),
    (
        "βασιλεία",
        "basileia.2",
        "reign",
        "the active exercise of royal authority",
        "BDAG",
        0.8,
        "dynamic",
    ),
    (
        "βασιλεία",
        "basileia.3",
        "kingship",
        "the status or position of being king",
        "Louw-Nida",
        0.5,
        "status",
    ),
    (
        "βασιλεία",
        "basileia.4",
        "empire",
        "dominion, realm of sovereign power (political register)",
        "LSJ",
        0.4,
        "political",
    ),
    # οὐρανός - heaven/sky ambiguity
    (
        "οὐρανός",
        "ouranos.1",
        "heaven",
        "the abode of God, transcendent realm",
        "BDAG",
        0.85,
        "religious",
    ),
    (
        "οὐρανός",
        "ouranos.2",
        "sky",
        "the visible firmament above",
        "BDAG",
        0.7,
        "physical",
    ),
    (
        "οὐρανός",
        "ouranos.3",
        "heavens",
        "circumlocution for God (Jewish usage avoiding divine name)",
        "BDAG",
        0.75,
        "circumlocution",
    ),
    # θεός
    (
        "θεός",
        "theos.1",
        "God",
        "the one true God of Israel",
        "BDAG",
        0.95,
        "religious",
    ),
    (
        "θεός",
        "theos.2",
        "god",
        "a deity (in polytheistic context)",
        "BDAG",
        0.3,
        "general",
    ),
    # καιρός - timing nuances
    (
        "καιρός",
        "kairos.1",
        "opportune time",
        "a decisive or critical moment",
        "BDAG",
        0.85,
        "qualitative",
    ),
    (
        "καιρός",
        "kairos.2",
        "time",
        "a period of time, season",
        "BDAG",
        0.7,
        "duration",
    ),
    (
        "καιρός",
        "kairos.3",
        "appointed time",
        "divinely determined moment",
        "Louw-Nida",
        0.8,
        "eschatological",
    ),
    # πληρόω - fulfillment nuances
    (
        "πληρόω",
        "pleroo.1",
        "fulfill",
        "to bring to completion what was prophesied/promised",
        "BDAG",
        0.85,
        "prophetic",
    ),
    (
        "πληρόω",
        "pleroo.2",
        "fill",
        "to make full, fill up",
        "BDAG",
        0.6,
        "spatial",
    ),
    (
        "πληρόω",
        "pleroo.3",
        "complete",
        "to finish, bring to an end",
        "Louw-Nida",
        0.75,
        "temporal",
    ),
    # πιστεύω - believe/trust ambiguity
    (
        "πιστεύω",
        "pisteuo.1",
        "believe",
        "to consider something to be true",
        "BDAG",
        0.7,
        "cognitive",
    ),
    (
        "πιστεύω",
        "pisteuo.2",
        "trust",
        "to have confidence in, rely upon",
        "BDAG",
        0.8,
        "relational",
    ),
    (
        "πιστεύω",
        "pisteuo.3",
        "be faithful to",
        "to maintain loyalty and commitment",
        "Louw-Nida",
        0.6,
        "behavioral",
    ),
    # εὐαγγέλιον - gospel meanings
    (
        "εὐαγγέλιον",
        "euaggelion.1",
        "good news",
        "a message of good tidings",
        "BDAG",
        0.9,
        "message",
    ),
    (
        "εὐαγγέλιον",
        "euaggelion.2",
        "gospel",
        "the Christian message about Jesus",
        "BDAG",
        0.7,
        "religious",
    ),
    (
        "εὐαγγέλιον",
        "euaggelion.3",
        "proclamation",
        "imperial announcement of victory/accession (political usage)",
        "LSJ",
        0.5,
        "political",
    ),
    # μακάριος - blessed/happy
    (
        "μακάριος",
        "makarios.1",
        "blessed",
        "privileged recipient of divine favor",
        "BDAG",
        0.85,
        "religious",
    ),
    (
        "μακάριος",
        "makarios.2",
        "fortunate",
        "enjoying favorable circumstances",
        "BDAG",
        0.6,
        "general",
    ),
    (
        "μακάριος",
        "makarios.3",
        "happy",
        "in a state of well-being",
        "LSJ",
        0.5,
        "emotional",
    ),
    # πτωχός - poor nuances
    (
        "πτωχός",
        "ptochos.1",
        "poor",
        "economically destitute, lacking resources",
        "BDAG",
        0.85,
        "economic",
    ),
    (
        "πτωχός",
        "ptochos.2",
        "humble",
        "lowly in status or self-regard",
        "Louw-Nida",
        0.6,
        "social",
    ),
    (
        "πτωχός",
        "ptochos.3",
        "oppressed",
        "the afflicted poor (OT anawim concept)",
        "BDAG",
        0.7,
        "socio-religious",
    ),
    # πνεῦμα - spirit meanings
    (
        "πνεῦμα",
        "pneuma.1",
        "spirit",
        "the non-material part of a person",
        "BDAG",
        0.8,
        "anthropological",
    ),
    (
        "πνεῦμα",
        "pneuma.2",
        "Spirit",
        "the Holy Spirit, divine Spirit",
        "BDAG",
        0.75,
        "theological",
    ),
    (
        "πνεῦμα",
        "pneuma.3",
        "breath",
        "air in movement, wind",
        "BDAG",
        0.4,
        "physical",
    ),
    (
        "πνεῦμα",
        "pneuma.4",
        "disposition",
        "inner attitude or orientation",
        "Louw-Nida",
        0.7,
        "psychological",
    ),
    # πατήρ
    ("πατήρ", "pater.1", "father", "male parent", "BDAG", 0.9, "kinship"),
    ("πατήρ", "pater.2", "Father", "God as Father", "BDAG", 0.85, "theological"),
    (
        "πατήρ",
        "pater.3",
        "ancestor",
        "forefather, patriarch",
        "BDAG",
        0.5,
        "genealogical",
    ),
    # ἁγιάζω
    (
        "ἁγιάζω",
        "hagiazo.1",
        "make holy",
        "to set apart as sacred",
        "BDAG",
        0.85,
        "religious",
    ),
    (
        "ἁγιάζω",
        "hagiazo.2",
        "sanctify",
        "to purify, consecrate",
        "BDAG",
        0.8,
        "ritual",
    ),
    (
        "ἁγιάζω",
        "hagiazo.3",
        "treat as holy",
        "to regard and honor as sacred",
        "Louw-Nida",
        0.75,
        "attitudinal",
    ),
    # ὄνομα
    (
        "ὄνομα",
        "onoma.1",
        "name",
        "the proper designation of a person",
        "BDAG",
        0.9,
        "linguistic",
    ),
    (
        "ὄνομα",
        "onoma.2",
        "character",
        "the nature/reputation a name represents (Semitic concept)",
        "BDAG",
        0.7,
        "representative",
    ),
    # ἔρχομαι
    (
        "ἔρχομαι",
        "erchomai.1",
        "come",
        "to move toward the speaker/reference point",
        "BDAG",
        0.9,
        "spatial",
    ),
    (
        "ἔρχομαι",
        "erchomai.2",
        "arrive",
        "to reach a destination",
        "BDAG",
        0.8,
        "arrival",
    ),
    # Common function words
    ("γάρ", "gar.1", "for", "marker of cause or reason", "BDAG", 0.95, "conjunction"),
    ("καί", "kai.1", "and", "connective conjunction", "BDAG", 0.95, "conjunction"),
    ("καί", "kai.2", "also/even", "adverbial/emphatic use", "BDAG", 0.7, "adverbial"),
    ("ὁ", "ho.1", "the", "definite article", "BDAG", 0.99, "article"),
    ("ἐν", "en.1", "in", "marker of position within", "BDAG", 0.85, "spatial"),
    (
        "ἐν",
        "en.2",
        "by/with",
        "marker of instrument or means",
        "BDAG",
        0.6,
        "instrumental",
    ),
    ("ὅτι", "hoti.1", "because", "marker of cause", "BDAG", 0.7, "causal"),
    ("ὅτι", "hoti.2", "that", "marker of content clause", "BDAG", 0.8, "declarative"),
    ("αὐτός", "autos.1", "he/she/it", "third person pronoun", "BDAG", 0.9, "pronoun"),
    (
        "αὐτός",
        "autos.2",
        "self/same",
        "intensive or identifying use",
        "BDAG",
        0.6,
        "intensive",
    ),
    ("ἐγώ", "ego.1", "I/we", "first person pronoun", "BDAG", 0.99, "pronoun"),
    ("σύ", "su.1", "you", "second person pronoun", "BDAG", 0.99, "pronoun"),
    ("εἰμί", "eimi.1", "be", "copulative verb", "BDAG", 0.99, "copula"),
]

# Demo speech spans
DEMO_SPEECH_SPANS = [
    # (book, chapter, verse_start, verse_end, speaker, confidence, source)
    (
        "Matthew",
        3,
        2,
        2,
        "John the Baptist",
        1.0,
        "narrative context",
    ),  # Actually John, not Jesus
    ("Matthew", 4, 17, 17, "Jesus", 1.0, "narrative context"),
    ("Mark", 1, 15, 15, "Jesus", 1.0, "narrative context"),
    ("Matthew", 5, 3, 12, "Jesus", 1.0, "Sermon on the Mount"),
    ("Matthew", 6, 9, 13, "Jesus", 1.0, "Lord's Prayer"),
]

# Demo collocations: (lemma1, lemma2, frequency, context_type)
DEMO_COLLOCATIONS = [
    ("βασιλεία", "οὐρανός", 32, "clause"),
    ("βασιλεία", "θεός", 53, "clause"),
    ("μετανοέω", "βασιλεία", 3, "verse"),
    ("ἐγγίζω", "βασιλεία", 4, "clause"),
    ("καιρός", "πληρόω", 2, "clause"),
    ("πιστεύω", "εὐαγγέλιον", 5, "clause"),
    ("πτωχός", "πνεῦμα", 1, "clause"),
    ("μακάριος", "βασιλεία", 2, "verse"),
]
